import twitter
import os

TWITTER_API_KEY=os.environ.get('TWITTER_API_KEY')
TWITTER_SECRET_KEY=os.environ.get('TWITTER_SECRET_KEY')
TWITTER_ACCESS_TOKEN=os.environ.get('TWITTER_ACCESS_TOKEN')
TWITTER_SECRET_TOKEN=os.environ.get('TWITTER_SECRET_TOKEN')

print TWITTER_SECRET_TOKEN
print TWITTER_SECRET_KEY
print TWITTER_ACCESS_TOKEN
print TWITTER_API_KEY

auth = twitter.oauth.OAuth(TWITTER_ACCESS_TOKEN, TWITTER_SECRET_TOKEN, TWITTER_API_KEY, TWITTER_SECRET_KEY)
twitter_api = twitter.Twitter(auth=auth)

print twitter_api